CREATE TABLE IF NOT EXISTS colors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hex VARCHAR(6) NOT NULL UNIQUE,
    rgb VARCHAR(20) NOT NULL,
    ryb VARCHAR(20) NOT NULL,
    cmy VARCHAR(30) NOT NULL,
    parts VARCHAR(15) NOT NULL
);